name: Release

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write     # nodig voor trusted publishing
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish --publish-url https://test.pypi.org/legacy/